[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Shougo/neocomplete'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'NigoroJr/rsense'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'pocke/dicts'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'groenewege/vim-less'

[[plugins]]
repo = 'itchyny/lightline.vim'


